import { Montserrat, Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap-utilities.min.css";
import "bootstrap/dist/css/bootstrap-grid.min.css";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["600", "800"],
  styles: ["normal"],
  fallback: ["sans-serif"]
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  styles: ["normal"],
  fallback: ["sans-serif"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html className={`${montserrat.variable} ${poppins.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
