import { Montserrat, Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap-utilities.min.css";
import "bootstrap/dist/css/bootstrap-grid.min.css";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import {getMessages} from 'next-intl/server';
import CloudfretNewsletter from "@/sections/layout/cloudfret-newsletter";
import CloudfretFooter from "@/sections/layout/cloudfret-footer";
import CloudfretNavbar from "@/sections/layout/cloudfret-navbar";
import CloudfretOffer from "@/sections/layout/cloudfret-offer";
import PageLoader from "@/components/page-loader";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["600", "800"],
  styles: ["normal"],
  fallback: ["sans-serif"]
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  styles: ["normal"],
  fallback: ["sans-serif"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale} className={`${montserrat.variable} ${poppins.variable}`}>
        <body>
          <CloudfretOffer/>
          <CloudfretNavbar/>

          {children}

          <CloudfretNewsletter/>
          <CloudfretFooter/>
          <PageLoader/>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
